# Generated by Django 3.1.2 on 2020-11-13 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pertanyaan', '0002_question_detail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='answer',
            field=models.ManyToManyField(blank=True, to='pertanyaan.Answer'),
        ),
    ]
