# Generated by Django 3.1.2 on 2020-11-15 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Testi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('institusi', models.CharField(max_length=100)),
                ('testimoni', models.TextField(max_length=1000)),
                ('tanggal_testi', models.DateField(auto_now=True)),
            ],
        ),
        migrations.AddIndex(
            model_name='testi',
            index=models.Index(fields=['institusi', 'nama'], name='testi_testi_institu_db0e59_idx'),
        ),
        migrations.AddIndex(
            model_name='testi',
            index=models.Index(fields=['nama'], name='nama_idx'),
        ),
    ]
