# Generated by Django 3.1.2 on 2020-11-08 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pendonor',
            name='method',
            field=models.CharField(choices=[('Transfer Bank', 'Transfer Bank'), ('Pepew Pay', 'Pepew Pay'), ('pos', 'pos')], max_length=100, null=True),
        ),
    ]
