# Generated by Django 3.1.1 on 2020-11-13 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20201108_1436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pendonor',
            name='method',
            field=models.CharField(choices=[('Transfer Bank', 'Transfer Bank'), ('Pepew Pay', 'Pepew Pay'), ('Go Pew', 'Go Pew'), ('OPEW', 'OPEW'), ('Pew Aja', 'Pew Aja')], max_length=100, null=True),
        ),
    ]
