# Generated by Django 3.1.2 on 2020-11-13 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20201113_0902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pendonor',
            name='messages',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
