# Generated by Django 3.1.2 on 2020-11-08 07:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DaftarPendonor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pendonor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.pendonor')),
            ],
        ),
    ]
