# Generated by Django 3.1.2 on 2020-11-19 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donasi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donasi',
            name='kebutuhan',
        ),
    ]
