# Generated by Django 3.1.2 on 2020-11-19 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donasi', '0002_remove_donasi_kebutuhan'),
    ]

    operations = [
        migrations.AddField(
            model_name='donasi',
            name='image',
            field=models.ImageField(null=True, upload_to='img_storage/'),
        ),
    ]
